name: Build Docker images on Git tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Extraire la version depuis le tag Git (ex: v1.2.3)
      - name: Extract version from Git tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build server image
        run: |
          docker build \
            -t erapport-server:${VERSION} \
            ./server

      - name: Build client image
        run: |
          docker build \
            -t erapport-client:${VERSION} \
            ./client
