name: Build Docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Récupère un tag court basé sur le SHA du commit
      - name: Set version tag
        id: vars
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build server image
        run: |
          docker build \
            -t erapport-server:${VERSION} \
            -t erapport-server:latest \
            ./server

      - name: Build client image
        run: |
          docker build \
            -t erapport-client:${VERSION} \
            -t erapport-client:latest \
            ./client
